version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest' #最新版npm
    restart: unless-stopped
    ports:
      - '80:56960'
      - '81:56961'
      - '443:56962'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  maccms10:
      volumes:
          - ./mnt/maccms:/data
          - ./mnt/maccms/template:/opt/maccms10/template
      ports:
          - '7878:56963'
      image: gs0245/maccms10
        #network_mode: host (optional)
      restart: always